version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet" ]
      interval: 10s
      timeout: 5s
      retries: 5


  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minio_user minio_password;
      mc mb --ignore-existing local/filespark-bucket;
      exit 0;
      "

  filespark-storage:
    build: .
    container_name: filespark-storage
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
      minio:
        condition: service_started
      minio-init:
        condition: service_completed_successfully

    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minio_user
      MINIO_SECRET_KEY: minio_password
      MINIO_BUCKET: filespark-bucket
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/filesparkdb

volumes:
  mongo_data:
  minio_data:
