services:

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: filespark-minio
    environment:
      MINIO_ACCESS_KEY: minio_user
      MINIO_SECRET_KEY: minio_password
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  filespark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filespark-service
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minio_user
      MINIO_SECRET_KEY: minio_password
    ports:
      - "8080:8080"
    depends_on:
      - minio

volumes:
  minio_data:
